language: android
sudo: required
dist: UserAgency
jdk: oraclejdk8

before_script:
  - chmod +x gradlew

android:
  components:
    - build-tools-28.0.3
    - android-28
    - tools
    - add-on
    - extra
    # - platform-tools
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17